## Configuração Local (Máquina do Desenvolvedor) ##
server:
  host: localhost
  port: 8030

## Eureka - Service Discovery
eureka:
  host: localhost
  port: 8081
  name: eureka
  client:
    enabled: false

## DATABASE
database:
  #  host: contazapdev1.cpzwhgxqvzwg.us-west-2.rds.amazonaws.com
  host: contazapstg.crwx1osmvkb3.us-west-2.rds.amazonaws.com
  port: 5432
  name: zap_webservices
  username: contazaphm
  password: 's$q2ubt_CEEqgMMucNXE*:S>X5'

## Config Application and Database
spring:
  application:
    name: zap-lotes
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}?ApplicationName=${spring.application.name}
    username: ${database.username}
    password: ${database.password}

## MICROSERVIÇOS
zap-microservices:
  #  base-url: https://apigateway.dev.contazap.com/gateway
  base-url: https://apigateway.stg.contazap.com/gateway
  authentication:
    username: zapinternal
  zap-auth:
    uri: ${zap-microservices.base-url}/zap-auth

## SECURITY
security:
  jwt-key: CmRJURP09R5PVI30XN+wLkw/S3jhtaIAfKfvY0WhsHUJ7Ox04pY7e0TzndyY8zalIgTsKtOLXG1Mz+dqs7U7GM6QLW7DqYhmiLrjYUkw05++R6KKMUOH4kYgNxvMwvi5SoIXpnoCFBa5heoA+edsA111+YTOxwlSlcjeAKvARJGr2gIgH+VSHQUYHAoB02b48GmX+mtTk5MWzJcVxy1dDaSM2Su7mkmciy8zFugm8t4wCSde+OjoYhtCLQ0Fgy/RiPeqw0B/d30BA2ks6L31ggL2y6no6XLMlLITvooJzlOE3A6mYMYbKi1skEqdtxQKidWvLjrx561TuART4cG2Dg==
  username: zapapi
  password: Ap1Z@p

## OpenFeign
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

## LOGS
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    root: INFO
    com.zap.contadigital: TRACE
    com.sample.feign.demofeigncustomconfig: INFO
    org.springframework.web.client: INFO
    org.springframework.security.oauth2: INFO
    com.zap.contadigital.contas.client: DEBUG
